id: P5F95F4CF
initial_creation_type: ocr
source_metadata:
  volumes:
    538be5c4c3ee4b7281a2c2ef065bdd59:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: རིགས་པའི་ཐིགས་པ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1198
      volume_number: 97
